# Generated by Django 5.1.3 on 2026-01-02 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='gender',
            field=models.CharField(choices=[('male', 'Чоловічий'), ('female', 'Жіночий')], default='female', max_length=10, verbose_name='Рід'),
        ),
    ]
