# Generated by Django 5.1.3 on 2026-01-03 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0002_add_gender_to_guest'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('invitation', 'question', 'choice'), name='unique_answer'),
        ),
    ]
