# Generated by Django 5.1.3 on 2026-01-03 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0003_alter_answer_unique_together_answer_unique_answer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together=set(),
        ),
    ]
